// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $ai from "./routes/ai.tsx";
import * as $bi from "./routes/bi.tsx";
import * as $bs from "./routes/bs.tsx";
import * as $cg from "./routes/cg.tsx";
import * as $ci from "./routes/ci.tsx";
import * as $di from "./routes/di.tsx";
import * as $fa from "./routes/fa.tsx";
import * as $fc from "./routes/fc.tsx";
import * as $fi from "./routes/fi.tsx";
import * as $gi from "./routes/gi.tsx";
import * as $go from "./routes/go.tsx";
import * as $gr from "./routes/gr.tsx";
import * as $hi from "./routes/hi.tsx";
import * as $hi2 from "./routes/hi2.tsx";
import * as $im from "./routes/im.tsx";
import * as $index from "./routes/index.tsx";
import * as $io from "./routes/io.tsx";
import * as $io5 from "./routes/io5.tsx";
import * as $lu from "./routes/lu.tsx";
import * as $md from "./routes/md.tsx";
import * as $ri from "./routes/ri.tsx";
import * as $rx from "./routes/rx.tsx";
import * as $si from "./routes/si.tsx";
import * as $sl from "./routes/sl.tsx";
import * as $tb from "./routes/tb.tsx";
import * as $tfi from "./routes/tfi.tsx";
import * as $ti from "./routes/ti.tsx";
import * as $vsc from "./routes/vsc.tsx";
import * as $wi from "./routes/wi.tsx";
import * as $Counter from "./islands/Counter.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/ai.tsx": $ai,
    "./routes/bi.tsx": $bi,
    "./routes/bs.tsx": $bs,
    "./routes/cg.tsx": $cg,
    "./routes/ci.tsx": $ci,
    "./routes/di.tsx": $di,
    "./routes/fa.tsx": $fa,
    "./routes/fc.tsx": $fc,
    "./routes/fi.tsx": $fi,
    "./routes/gi.tsx": $gi,
    "./routes/go.tsx": $go,
    "./routes/gr.tsx": $gr,
    "./routes/hi.tsx": $hi,
    "./routes/hi2.tsx": $hi2,
    "./routes/im.tsx": $im,
    "./routes/index.tsx": $index,
    "./routes/io.tsx": $io,
    "./routes/io5.tsx": $io5,
    "./routes/lu.tsx": $lu,
    "./routes/md.tsx": $md,
    "./routes/ri.tsx": $ri,
    "./routes/rx.tsx": $rx,
    "./routes/si.tsx": $si,
    "./routes/sl.tsx": $sl,
    "./routes/tb.tsx": $tb,
    "./routes/tfi.tsx": $tfi,
    "./routes/ti.tsx": $ti,
    "./routes/vsc.tsx": $vsc,
    "./routes/wi.tsx": $wi,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
