// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/ai.tsx";
import * as $1 from "./routes/bi.tsx";
import * as $2 from "./routes/bs.tsx";
import * as $3 from "./routes/cg.tsx";
import * as $4 from "./routes/ci.tsx";
import * as $5 from "./routes/di.tsx";
import * as $6 from "./routes/fa.tsx";
import * as $7 from "./routes/fc.tsx";
import * as $8 from "./routes/fi.tsx";
import * as $9 from "./routes/gi.tsx";
import * as $10 from "./routes/go.tsx";
import * as $11 from "./routes/gr.tsx";
import * as $12 from "./routes/hi.tsx";
import * as $13 from "./routes/hi2.tsx";
import * as $14 from "./routes/im.tsx";
import * as $15 from "./routes/index.tsx";
import * as $16 from "./routes/io.tsx";
import * as $17 from "./routes/io5.tsx";
import * as $18 from "./routes/lu.tsx";
import * as $19 from "./routes/md.tsx";
import * as $20 from "./routes/ri.tsx";
import * as $21 from "./routes/rx.tsx";
import * as $22 from "./routes/si.tsx";
import * as $23 from "./routes/sl.tsx";
import * as $24 from "./routes/tb.tsx";
import * as $25 from "./routes/tfi.tsx";
import * as $26 from "./routes/ti.tsx";
import * as $27 from "./routes/vsc.tsx";
import * as $28 from "./routes/wi.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/ai.tsx": $0,
    "./routes/bi.tsx": $1,
    "./routes/bs.tsx": $2,
    "./routes/cg.tsx": $3,
    "./routes/ci.tsx": $4,
    "./routes/di.tsx": $5,
    "./routes/fa.tsx": $6,
    "./routes/fc.tsx": $7,
    "./routes/fi.tsx": $8,
    "./routes/gi.tsx": $9,
    "./routes/go.tsx": $10,
    "./routes/gr.tsx": $11,
    "./routes/hi.tsx": $12,
    "./routes/hi2.tsx": $13,
    "./routes/im.tsx": $14,
    "./routes/index.tsx": $15,
    "./routes/io.tsx": $16,
    "./routes/io5.tsx": $17,
    "./routes/lu.tsx": $18,
    "./routes/md.tsx": $19,
    "./routes/ri.tsx": $20,
    "./routes/rx.tsx": $21,
    "./routes/si.tsx": $22,
    "./routes/sl.tsx": $23,
    "./routes/tb.tsx": $24,
    "./routes/tfi.tsx": $25,
    "./routes/ti.tsx": $26,
    "./routes/vsc.tsx": $27,
    "./routes/wi.tsx": $28,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
